language: python
sudo: false
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
    - make init
    - pip install coveralls
script:
    - make test
after_script:
    - coveralls
